# Generated by Django 5.0.7 on 2024-07-28 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_Estudiante', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('carrera', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asistencia', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='FaltaAsistencia',
            fields=[
                ('id_FaltaAsistencia', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('Asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.asistencia')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.BigAutoField(primary_key=True, serialize=False)),
                ('semana', models.IntegerField(default=1)),
                ('monto', models.FloatField(default=0.0)),
                ('status', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('acronym', models.CharField(max_length=50)),
                ('web_page', models.URLField()),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='universities_created', to=settings.AUTH_USER_MODEL)),
                ('user_modified', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='universities_modified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('id_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pago')),
                ('in_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.university')),
            ],
        ),
        migrations.AddField(
            model_name='pago',
            name='id_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.university'),
        ),
        migrations.CreateModel(
            name='Justificacion',
            fields=[
                ('id_justificacion', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('FaltaAsistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.faltaasistencia')),
                ('id_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.university')),
            ],
        ),
        migrations.CreateModel(
            name='FaltaPago',
            fields=[
                ('semana', models.IntegerField(default=1)),
                ('status', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id_falta_pago', models.BigAutoField(primary_key=True, serialize=False)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pago')),
                ('id_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.university')),
            ],
        ),
        migrations.AddField(
            model_name='faltaasistencia',
            name='id_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.university'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.university'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.university'),
        ),
    ]
